package de.subhransu.openrouter.springai.image;

import org.springframework.ai.image.ImageGenerationMetadata;

/**
 * Per-image metadata from OpenRouter's Image API.
 *
 * @param mediaType the actual media type of the generated bytes (e.g. {@code image/png},
 * {@code image/svg+xml})
 * @param partialImageIndex the index of a streamed partial-image preview; {@code null}
 * for completed images
 * @author Subhransu De
 */
public record OpenRouterImageGenerationMetadata(String mediaType,
		Integer partialImageIndex) implements ImageGenerationMetadata {
}
